<?php
// Include the necessary libraries and init.php for database connection
require_once '../tcpdf/vendor/autoload.php';
require_once '../../app/init.php'; // Include database connection

// Create new PDF document
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// Set document information
$pdf->SetCreator('Logistic 2');
$pdf->SetAuthor('Hotel Paradise');
$pdf->SetTitle('Contract Report');
$pdf->SetSubject('Detailed Report of Contracts');
$pdf->SetKeywords('TCPDF, PDF, contracts, report, Hotel Paradise');

// Set default header data
$pdf->SetHeaderData('', 0, 'Contract Report', 'Generated by Hotel Paradise - Logistic 2 System');

// Set header and footer fonts
$pdf->setHeaderFont([PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN]);
$pdf->setFooterFont([PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA]);

// Set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// Set margins
$pdf->SetMargins(15, 27, 15);
$pdf->SetHeaderMargin(5);
$pdf->SetFooterMargin(10);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, 15);

// Set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// Add a page
$pdf->AddPage();

// Title of the report
$pdf->SetFont('helvetica', 'B', 16);
$pdf->Cell(0, 15, 'Contract Report', 0, 1, 'C');
$pdf->Ln(5); // Add some space after title

// Set font for content - Use DejaVu Sans for better Unicode support
$pdf->SetFont('dejavusans', '', 10);

// Fetch contract data from the database
$contracts = $DB->SELECT("contracts", "*", "ORDER BY contract_id DESC");

// Check if there are contracts
if (!empty($contracts)) {
    // HTML content for the table
    $html = '<table border="1" cellpadding="5">
             <thead>
                 <tr style="background-color:#f2f2f2;">
                     <th width="5%">#</th>
                     <th width="15%">Contract ID</th>
                     <th width="20%">Vendor Name</th>
                     <th width="25%">Terms</th>
                     <th width="10%">Start Date</th>
                     <th width="10%">End Date</th>
                     <th width="10%">Status</th>
                     <th width="10%">Renewal Date</th>
                 </tr>
             </thead>
             <tbody>';

    // Populate the table with data from the database
    $i = 1;
    foreach ($contracts as $contract) {
        // Fetch vendor information from `users` where role is `VENDOR`
        $vendor = $DB->SELECT_ONE_WHERE("users", "vendor_name", array("user_id" => $contract['vendor_id']));
        $vendorName = isset($vendor['vendor_name']) ? htmlspecialchars($vendor['vendor_name']) : 'Unknown Vendor';

        // Add the row to the table, handling null values gracefully
        $html .= '<tr>
                     <td>' . $i++ . '</td>
                     <td>' . htmlspecialchars($contract['contract_id'] ?? '') . '</td>
                     <td>' . $vendorName . '</td>
                     <td>' . htmlspecialchars($contract['contract_terms'] ?? '') . '</td>
                     <td>' . htmlspecialchars($contract['start_date'] ?? '') . '</td>
                     <td>' . htmlspecialchars($contract['end_date'] ?? '') . '</td>
                     <td>' . htmlspecialchars($contract['status'] ?? '') . '</td>
                     <td>' . htmlspecialchars($contract['renewal_date'] ?? '') . '</td>
                 </tr>';
    }

    $html .= '</tbody></table>';

    // Print the HTML content to the PDF
    $pdf->writeHTML($html, true, false, true, false, '');
} else {
    // If there are no contracts, display a message
    $pdf->Write(0, 'No contracts available.', '', 0, 'C', true);
}

// Output the PDF to the browser
$pdf->Output('contract_report.pdf', 'I'); // 'I' to display in browser, 'D' to download
