<?php
// Include the necessary libraries and init.php for database connection
require_once '../tcpdf/vendor/autoload.php';
require_once '../../app/init.php'; // Include database connection

// Create new PDF document
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// Set document information
$pdf->SetCreator('Logistic 2');
$pdf->SetAuthor('Hotel Paradise');
$pdf->SetTitle('Contract Report');
$pdf->SetSubject('Detailed Report of Contracts');
$pdf->SetKeywords('TCPDF, PDF, contracts, report, Hotel Paradise');

// Set default header data
$pdf->SetHeaderData('', 0, 'Contract Report', 'Generated by Hotel Paradise - Logistic 2 System');

// Set header and footer fonts
$pdf->setHeaderFont([PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN]);
$pdf->setFooterFont([PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA]);

// Set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// Set margins
$pdf->SetMargins(10, 20, 10);
$pdf->SetHeaderMargin(10);
$pdf->SetFooterMargin(10);

// Set auto page breaks
$pdf->SetAutoPageBreak(true, 10);
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// Add a page and set the font for the title
$pdf->AddPage();
$pdf->SetFont('helvetica', 'B', 16);
$pdf->Cell(0, 10, 'Contract Report', 0, 1, 'C');
$pdf->Ln(5); // Add some space after the title

// Introduction text
$pdf->SetFont('dejavusans', '', 10);
$pdf->Write(0, 'Detailed overview of active and completed contracts.', '', 0, 'C', true);
$pdf->Ln(5);

// Fetch contract data from the database
$contracts = $DB->SELECT("contracts", "*", "ORDER BY contract_id DESC");

// Check if there are contracts
if (!empty($contracts)) {
    // HTML content for the table
    $html = '<h3 style="text-align:center; color:#198754;">Contract Details</h3>
             <table border="1" cellpadding="5">
                <thead>
                    <tr style="background-color:#198754; color:#ffffff; text-align:center;">
                        <th>#</th>
                        <th>Contract ID</th>
                        <th>Vendor Name</th>
                        <th>Terms</th>
                        <th>Start Date</th>
                        <th>End Date</th>
                        <th>Status</th>
                        <th>Renewal Date</th>
                    </tr>
                </thead>
                <tbody>';

    // Populate table with data from the database
    $i = 1;
    foreach ($contracts as $contract) {
        // Fetch vendor information from `users` where role is `VENDOR`
        $vendor = $DB->SELECT_ONE_WHERE("users", "vendor_name", array("user_id" => $contract['vendor_id']));
        $vendorName = isset($vendor['vendor_name']) ? htmlspecialchars($vendor['vendor_name'], ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8') : 'Unknown Vendor';

        // Add each row to the HTML content, handling null values gracefully
        $html .= '<tr>
                     <td align="center">' . $i++ . '</td>
                     <td>' . htmlspecialchars($contract['contract_id'] ?? '', ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8') . '</td>
                     <td>' . $vendorName . '</td>
                     <td>' . htmlspecialchars($contract['contract_terms'] ?? '', ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8') . '</td>
                     <td align="center">' . htmlspecialchars($contract['start_date'] ?? '', ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8') . '</td>
                     <td align="center">' . htmlspecialchars($contract['end_date'] ?? '', ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8') . '</td>
                     <td align="center">' . htmlspecialchars($contract['status'] ?? '', ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8') . '</td>
                     <td align="center">' . htmlspecialchars($contract['renewal_date'] ?? '', ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8') . '</td>
                 </tr>';
    }

    $html .= '</tbody></table>';

    // Output the HTML content to the PDF
    $pdf->writeHTML($html, true, false, true, false, '');
} else {
    // If there are no contracts, display a message
    $pdf->SetFont('helvetica', 'I', 12);
    $pdf->Cell(0, 10, 'No contracts available.', 0, 1, 'C');
}

// Output the PDF to the browser
$pdf->Output('contract_report.pdf', 'I'); // 'I' to display in browser, 'D' to download
exit;
