<div class="container mt-4 py-5">
    <!-- Cards Section -->
    <div class="row text-center">
        <!-- Create New Requisition Card -->
        <div class="col-md-4 mb-3">
            <div class="card border-0 shadow-sm h-100">
                <div class="card-body">
                    <i class="fas fa-file-invoice fa-2x text-success mb-3"></i>
                    <h6 class="card-title">Create New Requisition</h6>
                    <p class="card-text text-muted small">Quick access to create a new purchase requisition.</p>
                    <!-- Button to Open Modal -->
                    <button id="btnCreateRequisition" class="btn btn-sm btn-success">Create Requisition</button>
                </div>
            </div>
        </div>

        <!-- View Active Requisitions Card -->
        <div class="col-md-4 mb-3">
            <div class="card border-0 shadow-sm h-100">
                <div class="card-body">
                    <i class="fas fa-eye fa-2x text-success mb-3"></i>
                    <h6 class="card-title">View Active Requisitions</h6>
                    <p class="card-text text-muted small">Monitor and manage active purchase requisitions.</p>
                    <!-- Button to Load Requisitions -->
                    <button id="btnViewRequisitions" class="btn btn-sm btn-success">View Requisitions</button>
                </div>
            </div>
        </div>

        <!-- Export Requisitions Card -->
        <div class="col-md-4 mb-3">
            <div class="card border-0 shadow-sm h-100">
                <div class="card-body">
                    <i class="fas fa-download fa-2x text-success mb-3"></i>
                    <h6 class="card-title">Export Requisitions</h6>
                    <p class="card-text text-muted small">Export requisition data to CSV or Excel.</p>
                    <!-- Button to Export Requisitions -->
                    <button id="btnExportRequisitions" class="btn btn-sm btn-success">Export Requisitions</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Requisition Table Section -->
    <div class="table-responsive mt-4">
        <table id="requisitionTable" class="table table-bordered table-hover table-sm shadow-sm">
            <thead class="thead-light text-success">
                <tr>
                    <th>#</th>
                    <th>Requisition ID</th>
                    <th>Department</th>
                    <th>Item Description</th>
                    <th>Quantity</th>
                    <th>Unit of Measure</th>
                    <th>Priority Level</th>
                    <th>Requested Date</th>
                    <th>Required Date</th>
                    <th>Status</th>
                    <th>Remarks</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <!-- Rows will be dynamically generated by JavaScript -->
            </tbody>
        </table>
    </div>

    <!-- Modal for Creating and Editing Requisition -->
    <div class="modal fade" id="createRequisitionModal" tabindex="-1" aria-labelledby="createRequisitionModalLabel"
        aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="createRequisitionModalLabel">Create New Purchase Requisition</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="requisitionForm">
                        <input type="hidden" id="requisitionId" name="requisition_id"> <!-- Hidden field for ID -->
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="department" class="form-label">Department</label>
                                <input type="text" class="form-control" id="department" name="department" required>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="itemDescription" class="form-label">Item Description</label>
                                <input type="text" class="form-control" id="itemDescription" name="item_description"
                                    required>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4 mb-3">
                                <label for="quantity" class="form-label">Quantity</label>
                                <input type="number" class="form-control" id="quantity" name="quantity" required>
                            </div>
                            <div class="col-md-4 mb-3">
                                <label for="unitOfMeasure" class="form-label">Unit of Measure</label>
                                <input type="text" class="form-control" id="unitOfMeasure" name="unit_of_measure"
                                    required>
                            </div>
                            <div class="col-md-4 mb-3">
                                <label for="priorityLevel" class="form-label">Priority Level</label>
                                <select class="form-select" id="priorityLevel" name="priority_level" required>
                                    <option value="High">High</option>
                                    <option value="Medium">Medium</option>
                                    <option value="Low">Low</option>
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="requestedDate" class="form-label">Requested Date</label>
                                <input type="date" class="form-control" id="requestedDate" name="requested_date"
                                    required>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="requiredDate" class="form-label">Required Date</label>
                                <input type="date" class="form-control" id="requiredDate" name="required_date" required>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="status" class="form-label">Status</label>
                                <select class="form-select" id="status" name="status" required>
                                    <option value="Pending">Pending</option>
                                    <option value="Approved">Approved</option>
                                    <option value="Ordered">Ordered</option>
                                </select>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="remarks" class="form-label">Remarks</label>
                                <textarea class="form-control" id="remarks" name="remarks"></textarea>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-success">Submit Requisition</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>