<?php
// Include the TCPDF library and init.php for database connection
require_once '../tcpdf/vendor/autoload.php';
require_once '../../app/init.php'; // Include database connection

// Create new PDF document
$pdf = new TCPDF();

// Set document information
$pdf->SetCreator('Your System');
$pdf->SetAuthor('Hotel Paradise');
$pdf->SetTitle('Purchase Order Report');
$pdf->SetSubject('Generated Report');
$pdf->SetKeywords('TCPDF, PDF, report, purchase order');

// Set default header data
$pdf->SetHeaderData('', 0, 'Purchase Order Report', 'Generated by Hotel Paradise Logistic 2');

// Set header and footer fonts
$pdf->setHeaderFont([PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN]);
$pdf->setFooterFont([PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA]);

// Set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// Set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// Set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// Add a page
$pdf->AddPage();

// Set font for content - Use DejaVu Sans for better Unicode support
$pdf->SetFont('dejavusans', '', 10);

// Title of the report
$pdf->SetFont('helvetica', 'B', 16);
$pdf->Cell(0, 15, 'Purchase Order Report', 0, 1, 'C');
$pdf->Ln(5); // Add some space after title

$pdf->SetFont('dejavusans', '', 10);
$pdf->Write(0, 'Generated report for all purchase orders.', '', 0, 'C', true);
$pdf->Ln(5);

// Fetch data from the database (purchaseorder table)
$purchaseOrders = $DB->SELECT("purchaseorder", "*", "ORDER BY po_id DESC");

// HTML content for the table
$html = '<table border="1" cellpadding="5">
         <thead>
             <tr>
                 <th>#</th>
                 <th>PO ID</th>
                 <th>Vendor Name</th>
                 <th>Items</th>
                 <th>Quantity</th>
                 <th>Unit Price</th>
                 <th>Total Cost</th>
                 <th>Order Date</th>
                 <th>Delivery Date</th>
                 <th>Status</th>
             </tr>
         </thead>
         <tbody>';

// Populate the table with data from the database
$i = 1;
foreach ($purchaseOrders as $order) {
    $statusBadge = $order['status'] == 'Delivered' ? 'Delivered' : ($order['status'] == 'Cancelled' ? 'Cancelled' : 'Ordered');
    $html .= '<tr>
             <td>' . $i++ . '</td>
             <td>' . CHARS($order['po_id'] ?? '') . '</td>
             <td>' . CHARS($order['vendor_name'] ?? '') . '</td>
             <td>' . CHARS($order['items'] ?? '') . '</td>
             <td>' . CHARS($order['quantity'] ?? '') . '</td>
             <td>₱' . number_format($order['unit_price'] ?? 0, 2) . '</td>
             <td>₱' . number_format($order['total_cost'] ?? 0, 2) . '</td>
             <td>' . CHARS($order['order_date'] ?? '') . '</td>
             <td>' . (!empty($order['delivery_date']) ? htmlspecialchars($order['delivery_date']) : 'No date available') . '</td>
             <td>' . $statusBadge . '</td>
         </tr>';
}

$html .= '</tbody></table>';

// Print the HTML content to the PDF
$pdf->writeHTML($html, true, false, true, false, '');

// Output the PDF to the browser
$pdf->Output('purchase_order_report.pdf', 'I'); // 'I' to display in the browser, 'D' to force download
