<?php
require_once '../tcpdf/vendor/autoload.php';
require_once '../../app/init.php'; // Include database connection or init script

// Create new PDF document
$pdf = new TCPDF();

// Set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Hotel and Restaurant');
$pdf->SetTitle('User Report');
$pdf->SetSubject('Generated User Report');
$pdf->SetKeywords('TCPDF, PDF, report, user');

// Set default header data
$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, 'User Report', 'Generated by Hotel Paradise Logistic 2');

// Set header and footer fonts
$pdf->setHeaderFont(array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// Set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// Set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// Set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// Add a page
$pdf->AddPage();

// Set font for content
$pdf->SetFont('helvetica', '', 10);

// Fetch data from the database (users)
$users = $DB->SELECT("users", "*", "ORDER BY id DESC");

// HTML content for the table
$html = '<h2>User Report</h2>
         <table border="1" cellpadding="5">
         <thead>
             <tr>
                 <th>#</th>
                 <th>User ID</th>
                 <th>Username</th>
                 <th>First Name</th>
                 <th>Last Name</th>
                 <th>Email</th>
                 <th>Contact</th>
                 <th>Role</th>
                 <th>Status</th>
             </tr>
         </thead>
         <tbody>';

// Populate the table with data from the database
$i = 1;
foreach ($users as $user) {
    $html .= '<tr>
                 <td>' . $i++ . '</td>
                 <td>' . CHARS($user['user_id']) . '</td>
                 <td>' . CHARS($user['username']) . '</td>
                 <td>' . CHARS($user['firstname']) . '</td>
                 <td>' . CHARS($user['lastname']) . '</td>
                 <td>' . CHARS($user['email']) . '</td>
                 <td>' . CHARS($user['contact']) . '</td>
                 <td>' . CHARS($user['role']) . '</td>
                 <td>' . CHARS($user['status']) . '</td>
             </tr>';
}

$html .= '</tbody></table>';

// Print the HTML content to the PDF
$pdf->writeHTML($html, true, false, true, false, '');

// Output the PDF
$pdf->Output('user_report.pdf', 'I'); // 'I' to display in the browser, 'D' to force download
