<?php
// Include the TCPDF library and init.php for database connection
require_once '../tcpdf/vendor/autoload.php';
require_once '../../app/init.php'; // Include database connection

// Create new PDF document
$pdf = new TCPDF();

// Set document information
$pdf->SetCreator(APP_NAME_LONG);
$pdf->SetAuthor('Hotel Paradise');
$pdf->SetTitle('Budget Approval Report');
$pdf->SetSubject('Generated Report');
$pdf->SetKeywords('TCPDF, PDF, report, budget, approval');

// Set default header data (replace with your logo if needed)
$pdf->SetHeaderData('', 0, 'Budget Approval Report', 'Generated by Hotel Paradise Logistic 2');

// Set header and footer fonts
$pdf->setHeaderFont([PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN]);
$pdf->setFooterFont([PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA]);

// Set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// Set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// Set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// Add a page
$pdf->AddPage();

// Set font that supports the Peso sign
$pdf->SetFont('dejavusans', '', 10);

// Title of the report
$pdf->SetFont('dejavusans', 'B', 16); // DejaVuSans font for UTF-8 support
$pdf->Cell(0, 15, 'Budget Approval Report', 0, 1, 'C');
$pdf->Ln(5); // Add some space after title

$pdf->SetFont('dejavusans', '', 10);
$pdf->Write(0, 'Generate and review budget approval reports based on various filters.', '', 0, 'C', true);
$pdf->Ln(5);

// Fetch data from the database (budget_approval)
$approvals = $DB->SELECT("budget_approval", "*", "ORDER BY approval_id DESC");

// HTML content for the table
$html = '<table border="1" cellpadding="5">
         <thead>
             <tr>
                 <th>#</th>
                 <th>Approval ID</th>
                 <th>Requisition ID</th>
                 <th>Approved Amount</th>
                 <th>Approval Status</th>
                 <th>Approved By</th>
                 <th>Approval Date</th>
                 <th>Remarks</th>
             </tr>
         </thead>
         <tbody>';

// Populate the table with data from the database
$i = 1;
foreach ($approvals as $approval) {
    $statusBadge = $approval['approval_status'] == 'Approved' ? 'Approved' : ($approval['approval_status'] == 'Rejected' ? 'Rejected' : 'Pending');
    $html .= '<tr>
             <td>' . $i++ . '</td>
             <td>' . CHARS($approval['approval_id'] ?? '') . '</td>
             <td>' . CHARS($approval['requisition_id'] ?? '') . '</td>
             <td>₱' . number_format($approval['approved_amount'] ?? 0, 2) . '</td>
             <td>' . ($statusBadge ?? '') . '</td>
             <td>' . CHARS($approval['approved_by'] ?? '') . '</td>
             <td>' . CHARS($approval['approval_date'] ?? '') . '</td>
             <td>' . CHARS($approval['approval_comments'] ?? '') . '</td>
         </tr>';
}

$html .= '</tbody></table>';

// Print the HTML content to the PDF
$pdf->writeHTML($html, true, false, true, false, '');

// Output the PDF to the browser
$pdf->Output('budget_approval_report.pdf', 'I'); // 'I' to display in the browser, 'D' to force download
