<?php
// Include the TCPDF library and database connection
require_once '../tcpdf/vendor/autoload.php';
require_once '../../app/init.php'; // Include your database connection

// Create new PDF document
$pdf = new TCPDF();

// Set document information
$pdf->SetCreator('Hotel Paradise Logistic 2');
$pdf->SetAuthor('Hotel Paradise');
$pdf->SetTitle('Budget Approval Report');
$pdf->SetSubject('Generated Report');
$pdf->SetKeywords('TCPDF, PDF, report, budget, approval');

// Set default header data (add a logo if needed)
$pdf->SetHeaderData('', 0, 'Budget Approval Report', 'Generated by Hotel Paradise Logistic 2');

// Set header and footer fonts
$pdf->setHeaderFont([PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN]);
$pdf->setFooterFont([PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA]);

// Set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// Set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// Set auto page breaks
$pdf->SetAutoPageBreak(true, PDF_MARGIN_BOTTOM);

// Set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// Add a page
$pdf->AddPage();

// Set font for the content
$pdf->SetFont('dejavusans', '', 10);

// Title of the report
$pdf->SetFont('dejavusans', 'B', 16); // Use DejaVuSans font for UTF-8 support
$pdf->Cell(0, 15, 'Budget Approval Report', 0, 1, 'C');
$pdf->Ln(5); // Add some space after the title

// Introduction text
$pdf->SetFont('dejavusans', '', 10);
$pdf->Write(0, 'Generate and review budget approval reports based on various filters.', '', 0, 'C', true);
$pdf->Ln(5);

// Fetch data from the database (purchaserequisition with budget_approval)
$fields = "
    pr.requisition_id, pr.department, pr.item_description, pr.quantity, 
    pr.estimated_cost, ba.approved_amount, ba.approval_status, 
    ba.approved_by, ba.approval_date, ba.remarks AS approval_remarks
";
$options = "
    INNER JOIN budget_approval ba ON pr.requisition_id = ba.requisition_id 
    ORDER BY ba.approval_id DESC
";

$approvals = $DB->SELECT('purchaserequisition pr', $fields, $options);

// HTML content for the table
$html = '<table border="1" cellpadding="5">
         <thead>
             <tr>
                 <th>#</th>
                 <th>Requisition ID</th>
                 <th>Department</th>
                 <th>Item Description</th>
                 <th>Quantity</th>
                 <th>Estimated Cost</th>
                 <th>Approved Amount</th>
                 <th>Approval Status</th>
                 <th>Approved By</th>
                 <th>Approval Date</th>
                 <th>Remarks</th>
             </tr>
         </thead>
         <tbody>';

// Populate the table with data from the database
$i = 1;
foreach ($approvals as $approval) {
    // Sanitize and format the data for display
    $requisition_id = htmlspecialchars($approval['requisition_id'] ?? '');
    $department = htmlspecialchars($approval['department'] ?? '');
    $item_description = htmlspecialchars($approval['item_description'] ?? '');
    $quantity = htmlspecialchars($approval['quantity'] ?? '');
    $estimated_cost = number_format($approval['estimated_cost'] ?? 0, 2);
    $approved_amount = number_format($approval['approved_amount'] ?? 0, 2);
    $approval_status = htmlspecialchars($approval['approval_status'] ?? 'Pending');
    $approved_by = htmlspecialchars($approval['approved_by'] ?? 'N/A');
    $approval_date = htmlspecialchars($approval['approval_date'] ?? 'N/A');
    $approval_remarks = htmlspecialchars($approval['approval_remarks'] ?? 'No remarks');

    // Add the row to the HTML content
    $html .= '<tr>
                 <td>' . $i++ . '</td>
                 <td>' . $requisition_id . '</td>
                 <td>' . $department . '</td>
                 <td>' . $item_description . '</td>
                 <td>' . $quantity . '</td>
                 <td>₱' . $estimated_cost . '</td>
                 <td>₱' . $approved_amount . '</td>
                 <td>' . $approval_status . '</td>
                 <td>' . $approved_by . '</td>
                 <td>' . $approval_date . '</td>
                 <td>' . $approval_remarks . '</td>
             </tr>';
}

$html .= '</tbody></table>';

// Output the HTML content to the PDF
$pdf->writeHTML($html, true, false, true, false, '');

// Output the PDF to the browser
$pdf->Output('budget_approval_report.pdf', 'I'); // 'I' to display in the browser, 'D' to force download
