<?php
// Include the TCPDF library and database connection
require_once '../tcpdf/vendor/autoload.php';
require_once '../../app/init.php'; // Include your database connection

// Create new PDF document
$pdf = new TCPDF('P', 'mm', 'A4', true, 'UTF-8', false);

// Set document information
$pdf->SetCreator('Hotel Paradise Logistic 2');
$pdf->SetAuthor('Hotel Paradise');
$pdf->SetTitle('Budget Approval Report');
$pdf->SetHeaderData('', 0, 'Budget Approval Report', 'Generated by Hotel Paradise Logistic 2');

// Set header and footer fonts
$pdf->setHeaderFont([PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN]);
$pdf->setFooterFont([PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA]);

// Set default monospaced font and margins
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);
$pdf->SetMargins(10, 20, 10);
$pdf->SetHeaderMargin(10);
$pdf->SetFooterMargin(10);
$pdf->SetAutoPageBreak(true, 10);
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// Add a page and set the font for the content
$pdf->AddPage();
$pdf->SetFont('helvetica', '', 10);

// Report title
$pdf->Cell(0, 10, 'Budget Approval Report', 0, 1, 'C');
$pdf->Ln(5); // Add some space after the title

// Introduction text
$pdf->Write(0, 'Generate and review budget approval reports based on various filters.', '', 0, 'C', true);
$pdf->Ln(5);

// Fetch data from the database (purchaserequisition with budget_approval)
$fields = "
    pr.requisition_id, pr.department, pr.item_description, pr.quantity, 
    pr.estimated_cost, ba.approved_amount, ba.approval_status, 
    ba.approved_by, ba.approval_date, ba.remarks AS approval_remarks
";
$options = "
    INNER JOIN budget_approval ba ON pr.requisition_id = ba.requisition_id 
    ORDER BY ba.approval_id DESC
";
$approvals = $DB->SELECT('purchaserequisition pr', $fields, $options);

// Check if data exists
if (empty($approvals)) {
    $pdf->SetFont('helvetica', 'I', 12);
    $pdf->Cell(0, 10, 'No budget approvals found for the given criteria.', 0, 1, 'C');
} else {
    // HTML content for the styled table
    $html = '<h3 style="text-align:center; color:#198754;">Budget Approval Details</h3>
             <table border="1" cellpadding="5">
                <thead>
                    <tr style="background-color:#198754; color:#ffffff; text-align:center;">
                        <th>#</th>
                        <th>Requisition ID</th>
                        <th>Department</th>
                        <th>Item Description</th>
                        <th>Quantity</th>
                        <th>Estimated Cost</th>
                        <th>Approved Amount</th>
                        <th>Approval Status</th>
                        <th>Approved By</th>
                        <th>Approval Date</th>
                        <th>Remarks</th>
                    </tr>
                </thead>
                <tbody>';

    // Populate the table with data from the database
    $i = 1;
    foreach ($approvals as $approval) {
        // Sanitize and format the data for display
        $requisition_id = htmlspecialchars($approval['requisition_id'] ?? '', ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
        $department = htmlspecialchars($approval['department'] ?? '', ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
        $item_description = htmlspecialchars($approval['item_description'] ?? '', ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
        $quantity = htmlspecialchars($approval['quantity'] ?? '', ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
        $estimated_cost = '₱' . number_format($approval['estimated_cost'] ?? 0, 2);
        $approved_amount = '₱' . number_format($approval['approved_amount'] ?? 0, 2);
        $approval_status = htmlspecialchars($approval['approval_status'] ?? 'Pending', ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
        $approved_by = htmlspecialchars($approval['approved_by'] ?? 'N/A', ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
        $approval_date = htmlspecialchars($approval['approval_date'] ?? 'N/A', ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
        $approval_remarks = htmlspecialchars($approval['approval_remarks'] ?? 'No remarks', ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');

        // Add each row to the HTML content
        $html .= '<tr>
                     <td align="center">' . $i++ . '</td>
                     <td>' . $requisition_id . '</td>
                     <td>' . $department . '</td>
                     <td>' . $item_description . '</td>
                     <td align="center">' . $quantity . '</td>
                     <td align="right">' . $estimated_cost . '</td>
                     <td align="right">' . $approved_amount . '</td>
                     <td>' . $approval_status . '</td>
                     <td>' . $approved_by . '</td>
                     <td>' . $approval_date . '</td>
                     <td>' . $approval_remarks . '</td>
                 </tr>';
    }

    $html .= '</tbody></table>';

    // Output the HTML content to the PDF
    $pdf->writeHTML($html, true, false, true, false, '');
}

// Output the PDF to the browser
$pdf->Output('budget_approval_report.pdf', 'I'); // 'I' to display in the browser, 'D' to force download
exit;
