<?php
require_once '../tcpdf/vendor/autoload.php';
require_once '../../app/init.php'; // Include daatabase connection or init script

// Create new PDF document
$pdf = new TCPDF();

// Set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Hotel and Restaurant');
$pdf->SetTitle('Purchase Requisition Report');
$pdf->SetSubject('Generated Report');
$pdf->SetKeywords('TCPDF, PDF, report, requisition');

// Set default header data
$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, 'Purchase Requisition Report', 'Generated by Hotel Paradise Logistic 2');

// Set header and footer fonts
$pdf->setHeaderFont(array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// Set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// Set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// Set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// Add a page
$pdf->AddPage();

// Set font for content
$pdf->SetFont('helvetica', '', 10);

// Fetch data from the database (purchaserequisition)
$requisitions = $DB->SELECT("purchaserequisition", "*", "ORDER BY requisition_id DESC");

// HTML content for the table
$html = '<h2>Purchase Requisition Report</h2>
         <table border="1" cellpadding="5">
         <thead>
             <tr>
                 <th>#</th>
                 <th>Requisition ID</th>
                 <th>Department</th>
                 <th>Item Description</th>
                 <th>Quantity</th>
                 <th>Unit of Measure</th>
                 <th>Priority Level</th>
                 <th>Requested Date</th>
                 <th>Required Date</th>
                 <th>Status</th>
             </tr>
         </thead>
         <tbody>';

// Populate the table with data from the database
$i = 1;
foreach ($requisitions as $requisition) {
    $statusBadge = $requisition['status'] == 'Approve' ? 'Approved' : ($requisition['status'] == 'Decline' ? 'Declined' : 'Pending');
    $html .= '<tr>
                 <td>' . $i++ . '</td>
                 <td>' . CHARS($requisition['requisition_id']) . '</td>
                 <td>' . CHARS($requisition['department']) . '</td>
                 <td>' . CHARS($requisition['item_description']) . '</td>
                 <td>' . CHARS($requisition['quantity']) . '</td>
                 <td>' . CHARS($requisition['unit_of_measure']) . '</td>
                 <td>' . CHARS($requisition['priority_level']) . '</td>
                 <td>' . CHARS($requisition['requested_date']) . '</td>
                 <td>' . CHARS($requisition['required_date']) . '</td>
                 <td>' . $statusBadge . '</td>
             </tr>';
}

$html .= '</tbody></table>';

// Print the HTML content to the PDF
$pdf->writeHTML($html, true, false, true, false, '');

// Output the PDF
$pdf->Output('requisition_report.pdf', 'I'); // 'I' to display in the browser, 'D' to force download
